runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: static/css
- url: /email_templates
  static_dir: static/email_templates
- url: /font-awesome
  static_dir: static/font-awesome
- url: /fonts
  static_dir: static/fonts
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /locales
  static_dir: static/locales
- url: /.*
  script: main.app
# [END handlers]
