runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: app/static/css
- url: /email_templates
  static_dir: app/static/email_templates
- url: /font-awesome
  static_dir: app/static/font-awesome
- url: /fonts
  static_dir: app/static/fonts
- url: /img
  static_dir: app/static/img
- url: /js
  static_dir: app/static/js
- url: /locales
  static_dir: app/static/locales
- url: /.*
  script: app.main.app
# [END handlers]

libraries:
- name: MySQLdb
  version: "latest"
